### ISSUE TITLE
Add some way to restart and share after game

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/turdle#6]
Or maybe even a way to view the most recent N games?

**Comment by JamesGelok** [comment]
There already is a way to restart and share after game. Therefore this should be closed, or renamed to "Add some way to view the most recent N games".

If "view most recent N games" is implemented, [maybe the index generator](https://github.dev/bvaughn/turdle/blob/33a9250d6f1e68bee73b89af646c902cde785264/utils/words.js#L16) should try to avoid repeats.

----

P.S.: This project is truly a masterpiece, btw. Good shit

**Comment by bvaughn** [comment]
The trouble is that if you accidentally close the end of game modal, the only way to restart is to reload the page- and there’s no way at all to share the recent game.

PS Thanks! 🙂

**Comment by bvaughn** [comment]
> If "view most recent N games" is implemented, [maybe the index generator](https://github.dev/bvaughn/turdle/blob/33a9250d6f1e68bee73b89af646c902cde785264/utils/words.js#L16) should try to avoid repeats.

aa94f514c7c1999ca25395b4073d32ba56431cc7

**Comment by bvaughn** [comment]
48ab42511a55419ae90e03367112a3f71400798c
